name: Deploy Next.js to Production

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build with Next.js
        run: npm run build

      - name: Push to Target Repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_DEPLOY_TOKEN }} # PAT Github
        with:
          source-directory: "out"
          destination-github-username: "JinXVIII" # nama username
          destination-repository-name: "latihan-html" # branch tujuan
          user-email: your-email@example.com
          target-branch: main
